apiVersion: v1
data:
  nginx.conf: |+
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include mime.types;

        upstream k8s_cluster {
            least_conn;
            server {{.Values.backend.svcname}}:8000;
        }

        server {
            listen 443 ssl;
            server_name localhost;

            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                proxy_pass http://k8s_cluster;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
            }
            
            location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }

        server {
            listen 80;
            return 301 https://$host$request_uri;
        }
    }

kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
