apiVersion: v1
data:
  nginx.conf: |+
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include mime.types;

        upstream crc_cluster {
            least_conn;
            server backend-svc:8000;
        }

        server {
            listen 8443 ssl;
            server_name 127.0.0.1;

            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                proxy_pass http://crc_cluster;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
            }
        }

        server {
            listen 8080;
            server_name 127.0.0.1;
            return 301 https://$host$request_uri;
        }
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
